In [15]:
import pandas as pd
import numpy as n

In [25]:
df=pd.read_csv('scores.csv', comment='#', escapechar='\t')
for i in df:
    if i[0]=='\t':
        i==i[1:]
        df.rename(columns={i: i[1:]}, inplace=True)
df=df.loc[df['week']<=4, ['week','home','hmatch','htotal','away','amatch','atotal']] # PEKAN BERAPA
df

,week,home,hmatch,htotal,away,amatch,atotal
0,1,Bali United FC,1,0,PSS Sleman,1,3
1,1,Persis Solo,1,0,Persebaya Surabaya,1,3
2,1,Persib Bandung,1,1,Madura United FC,1,1
3,1,Dewa United FC,1,3,Arema FC,1,0
4,1,PS Barito Putera,1,3,Persita Tangerang,1,0
5,1,Rans Nusantara FC,1,3,Persikabo 1973,1,0
6,1,Persik Kediri,1,1,Borneo FC Samarinda,1,1
7,1,PSIS Semarang,1,3,Bhayangkara FC,1,0
8,1,Persija Jakarta,1,1,PSM Makassar,1,1
9,2,PSS Sleman,1,4,Persis Solo,1,1
10,2,Arema FC,1,1,Persib Bandung,1,2
11,2,Persebaya Surabaya,1,4,PS Barito Putera,1,4
12,2,PSM Makassar,1,1,Dewa United FC,1,6
13,2,Persita Tangerang,1,3,PSIS Semarang,1,3
14,2,Borneo FC Samarinda,1,4,Bali United FC,1,0
15,2,Madura United FC,1,4,Persik Kediri,1,1
16,2,Bhayangkara FC,1,0,Rans Nusantara FC,1,6
17,2,Persikabo 1973,1,1,Persija Jakarta,1,2
18,3,Persikabo 1973,2,1,PSM Makassar,2,4
19,3,PS Barito Putera,2,7,PSS Sleman,2,4
20,3,Persib Bandung,2,3,Dewa United FC,2,7
21,3,Rans Nusantara FC,2,6,Persita Tangerang,2,6
22,3,Persik Kediri,2,4,Arema FC,2,1
23,3,Persis Solo,2,4,Borneo FC Samarinda,2,4
24,3,Bali United FC,2,3,Madura United FC,2,4
25,3,PSIS Semarang,2,6,Persebaya Surabaya,2,4
26,3,Persija Jakarta,2,5,Bhayangkara FC,2,0
27,4,Borneo FC Samarinda,2,7,PS Barito Putera,2,7
28,4,PSS Sleman,2,5,PSIS Semarang,2,7
29,4,Dewa United FC,2,10,Persik Kediri,2,4
30,4,Arema FC,2,1,Bali United FC,2,6
31,4,Persita Tangerang,2,9,Persija Jakarta,2,5
32,4,PSM Makassar,2,7,Persib Bandung,2,3
33,4,Bhayangkara FC,2,0,Persikabo 1973,2,4
34,4,Persebaya Surabaya,2,5,Rans Nusantara FC,2,7
35,4,Madura United FC,2,7,Persis Solo,2,4

In [17]:
dff=df.groupby(["home","away"]).agg({'hmatch':['max'],'htotal':['max'],'week':['max']})
dff

                                        hmatch htotal week
                                           max    max  max
home                away
Arema FC            Bali United FC           2      1    4
                    Persib Bandung           1      1    2
Bali United FC      Madura United FC         2      3    3
                    PSS Sleman               1      0    1
Bhayangkara FC      Persikabo 1973           2      0    4
                    Rans Nusantara FC        1      0    2
Borneo FC Samarinda Bali United FC           1      4    2
                    PS Barito Putera         2      7    4
Dewa United FC      Arema FC                 1      3    1
                    Persik Kediri            2     10    4
Madura United FC    Persik Kediri            1      4    2
                    Persis Solo              2      7    4
PS Barito Putera    PSS Sleman               2      7    3
                    Persita Tangerang        1      3    1
PSIS Semarang       Bhayangkara FC           1      3    1
                    Persebaya Surabaya       2      6    3
PSM Makassar        Dewa United FC           1      1    2
                    Persib Bandung           2      7    4
PSS Sleman          PSIS Semarang            2      5    4
                    Persis Solo              1      4    2
Persebaya Surabaya  PS Barito Putera         1      4    2
                    Rans Nusantara FC        2      5    4
Persib Bandung      Dewa United FC           2      3    3
                    Madura United FC         1      1    1
Persija Jakarta     Bhayangkara FC           2      5    3
                    PSM Makassar             1      1    1
Persik Kediri       Arema FC                 2      4    3
                    Borneo FC Samarinda      1      1    1
Persikabo 1973      PSM Makassar             2      1    3
                    Persija Jakarta          1      1    2
Persis Solo         Borneo FC Samarinda      2      4    3
                    Persebaya Surabaya       1      0    1
Persita Tangerang   PSIS Semarang            1      3    2
                    Persija Jakarta          2      9    4
Rans Nusantara FC   Persikabo 1973           1      3    1
                    Persita Tangerang        2      6    3

# home matches count

In [18]:
#counth=df.groupby(["home"]).agg({'hmatch':['max'],'htotal':['max']}).sort_values(by=('htotal','max'), ascending=False).reset_index()
counth=df.groupby(["home"]).agg({'week':['max'],'hmatch':['max']}).sort_values(by=('week','max')).reset_index()
counth.columns=counth.columns.droplevel(1)
counth.index=counth.index +1
counth

                   home  week  hmatch
1     Rans Nusantara FC     3       2
2        Bali United FC     3       2
3           Persis Solo     3       2
4        Persikabo 1973     3       2
5         Persik Kediri     3       2
6       Persija Jakarta     3       2
7      PS Barito Putera     3       2
8         PSIS Semarang     3       2
9        Persib Bandung     3       2
10   Persebaya Surabaya     4       2
11             Arema FC     4       2
12    Persita Tangerang     4       2
13     Madura United FC     4       2
14       Dewa United FC     4       2
15  Borneo FC Samarinda     4       2
16       Bhayangkara FC     4       2
17           PSS Sleman     4       2
18         PSM Makassar     4       2

# away matches count

In [19]:
counta=df.groupby(["away"]).agg({'week':['max'],'amatch':['max']}).sort_values(by=('week','max')).reset_index()
counta.columns=counta.columns.droplevel(1)
counta.index=counta.index +1
counta

                   away  week  amatch
1              Arema FC     3       2
2    Persebaya Surabaya     3       2
3            PSS Sleman     3       2
4     Persita Tangerang     3       2
5      Madura United FC     3       2
6          PSM Makassar     3       2
7   Borneo FC Samarinda     3       2
8        Bhayangkara FC     3       2
9        Dewa United FC     3       2
10     PS Barito Putera     4       2
11        PSIS Semarang     4       2
12       Bali United FC     4       2
13       Persib Bandung     4       2
14      Persija Jakarta     4       2
15        Persik Kediri     4       2
16       Persikabo 1973     4       2
17          Persis Solo     4       2
18    Rans Nusantara FC     4       2