In [1]:
import pandas as pd
import matplotlib.pyplot as p
import numpy as n

In [2]:
df = pd.read_csv('scores.csv', comment='#', escapechar='\t')

# try chatgpt code
# Remove leading tabs from column names
df.rename(columns=lambda x: x.strip('\t ') if isinstance(x, str) else x, inplace=True)
df['city'] = df['city'].str.lstrip()
df

,week,day,month,year,home,hscore,hmatch,hpoint,htotal,away,ascore,amatch,apoint,atotal,stadium,city
0,1,1,7,2023,Bali United FC,0,1,0,0,PSS Sleman,1,1,3,3,Kapten I Wayan Dipta,Gianyar
1,1,1,7,2023,Persis Solo,2,1,0,0,Persebaya Surabaya,3,1,3,3,Manahan,Solo
2,1,2,7,2023,Persib Bandung,1,1,1,1,Madura United FC,1,1,1,1,Gelora Bandung Lautan Api,Bandung
3,1,2,7,2023,Dewa United FC,1,1,3,3,Arema FC,0,1,0,0,Indomilk Arena,Tangerang
4,1,2,7,2023,PS Barito Putera,2,1,3,3,Persita Tangerang,0,1,0,0,Demang Lehman,Martapura
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,33,25,4,2024,Arema FC,3,17,3,37,PSM Makassar,2,17,0,41,Kapten I Wayan Dipta,Gianyar
293,33,25,4,2024,Persib Bandung,2,17,3,62,Borneo FC Samarinda,1,16,0,70,Si Jalak Harupat,Bandung
294,33,26,4,2024,Persis Solo,1,17,0,47,Persita Tangerang,2,17,3,36,Manahan,Solo
295,33,26,4,2024,PSIS Semarang,3,17,3,53,Persikabo 1973,0,17,0,20,dr. H. Moch. Soebroto,Magelang
296,33,26,4,2024,Rans Nusantara FC,0,17,0,35,Persija Jakarta,1,17,3,45,Sultan Agung,Bantul

In [3]:
df.columns

Index(['week', 'day', 'month', 'year', 'home', 'hscore', 'hmatch', 'hpoint',
       'htotal', 'away', 'ascore', 'amatch', 'apoint', 'atotal', 'stadium',
       'city'],
      dtype='object')

In [3]:
club = sorted(df['home'].unique())
print(club)

['Arema FC', 'Bali United FC', 'Bhayangkara FC', 'Borneo FC Samarinda', 'Dewa United FC', 'Madura United FC', 'PS Barito Putera', 'PSIS Semarang', 'PSM Makassar', 'PSS Sleman', 'Persebaya Surabaya', 'Persib Bandung', 'Persija Jakarta', 'Persik Kediri', 'Persikabo 1973', 'Persis Solo', 'Persita Tangerang', 'Rans Nusantara FC']

In [5]:
for prit in range (len(club)):
    print(club[prit].strip('')+',')

Arema FC,
Bali United FC,
Bhayangkara FC,
Borneo FC Samarinda,
Dewa United FC,
Madura United FC,
PS Barito Putera,
PSIS Semarang,
PSM Makassar,
PSS Sleman,
Persebaya Surabaya,
Persib Bandung,
Persija Jakarta,
Persik Kediri,
Persikabo 1973,
Persis Solo,
Persita Tangerang,
Rans Nusantara FC,

In [6]:
home = (df['stadium']+','+df['city']).unique()
for prit in range (len(home)):
    print(home[prit].strip(','))

Kapten I Wayan Dipta,Gianyar
Manahan,Solo
Gelora Bandung Lautan Api,Bandung
Indomilk Arena,Tangerang
Demang Lehman,Martapura
Maguwoharjo,Sleman
Brawijaya,Kediri
Jatidiri,Semarang
Gelora Bung Karno,Jakarta Pusat
Gelora Bung Tomo,Surabaya
Gelora B. J. Habibie,Pare-pare
Segiri,Samarinda
Gelora Madura Ratu Pamelingan,Pamekasan
Patriot Chandra Bhaga,Bekasi
Pakansari,Bogor
Wibawa Mukti,Bekasi
Sriwedari,Solo
Gelora Bangkalan,Bangkalan

In [3]:
df.groupby(['home','stadium']).agg({'week':'count', 'hpoint':'sum'})

                                                   week  hpoint
home                stadium
Arema FC            Kapten I Wayan Dipta             17      22
Bali United FC      Kapten I Wayan Dipta             17      38
Bhayangkara FC      Patriot Chandra Bhaga            12       7
                    STIK Jakarta                      4       3
Borneo FC Samarinda Batakan                           4       6
                    Segiri                           13      35
Dewa United FC      Indomilk Arena                   16      28
Madura United FC    Gelora Bangkalan                 12      24
                    Gelora Madura Ratu Pamelingan     4       6
PS Barito Putera    Demang Lehman                    11      24
                    Sultan Agung                      6       9
PSIS Semarang       Jatidiri                         13      29
                    dr. H. Moch. Soebroto             4      10
PSM Makassar        Batakan                           5       9
                    Gelora B. J. Habibie             11      19
PSS Sleman          Maguwoharjo                      11      15
                    Manahan                           4       4
                    Sultan Agung                      1       1
Persebaya Surabaya  Gelora Bung Tomo                 16      24
Persib Bandung      Gelora Bandung Lautan Api        12      19
                    Si Jalak Harupat                  5      13
Persija Jakarta     Gelora Bung Karno                 5       8
                    Kapten I Wayan Dipta              3       6
                    Patriot Chandra Bhaga             8      14
Persik Kediri       Brawijaya                        17      33
Persikabo 1973      Kapten I Wayan Dipta              2       0
                    Pakansari                         2       1
                    Sultan Agung                      2       3
                    Wibawa Mukti                     10       8
Persis Solo         Kapten I Wayan Dipta              1       3
                    Maguwoharjo                       2       4
                    Manahan                          13      28
                    Sriwedari                         1       1
Persita Tangerang   Indomilk Arena                   15      24
                    Kapten I Wayan Dipta              1       1
Rans Nusantara FC   Maguwoharjo                      11      17
                    Sultan Agung                      6       2

In [4]:
df.groupby(['home','stadium']).agg({'week':'count', 'hpoint':'sum'}).sort_values(by='hpoint')

                                                   week  hpoint
home                stadium
Persikabo 1973      Kapten I Wayan Dipta              2       0
Persita Tangerang   Kapten I Wayan Dipta              1       1
PSS Sleman          Sultan Agung                      1       1
Persikabo 1973      Pakansari                         2       1
Persis Solo         Sriwedari                         1       1
Rans Nusantara FC   Sultan Agung                      6       2
Persis Solo         Kapten I Wayan Dipta              1       3
Persikabo 1973      Sultan Agung                      2       3
Bhayangkara FC      STIK Jakarta                      4       3
Persis Solo         Maguwoharjo                       2       4
PSS Sleman          Manahan                           4       4
Madura United FC    Gelora Madura Ratu Pamelingan     4       6
Persija Jakarta     Kapten I Wayan Dipta              3       6
Borneo FC Samarinda Batakan                           4       6
Bhayangkara FC      Patriot Chandra Bhaga            12       7
Persikabo 1973      Wibawa Mukti                     10       8
Persija Jakarta     Gelora Bung Karno                 5       8
PS Barito Putera    Sultan Agung                      6       9
PSM Makassar        Batakan                           5       9
PSIS Semarang       dr. H. Moch. Soebroto             4      10
Persib Bandung      Si Jalak Harupat                  5      13
Persija Jakarta     Patriot Chandra Bhaga             8      14
PSS Sleman          Maguwoharjo                      11      15
Rans Nusantara FC   Maguwoharjo                      11      17
PSM Makassar        Gelora B. J. Habibie             11      19
Persib Bandung      Gelora Bandung Lautan Api        12      19
Arema FC            Kapten I Wayan Dipta             17      22
PS Barito Putera    Demang Lehman                    11      24
Madura United FC    Gelora Bangkalan                 12      24
Persita Tangerang   Indomilk Arena                   15      24
Persebaya Surabaya  Gelora Bung Tomo                 16      24
Dewa United FC      Indomilk Arena                   16      28
Persis Solo         Manahan                          13      28
PSIS Semarang       Jatidiri                         13      29
Persik Kediri       Brawijaya                        17      33
Borneo FC Samarinda Segiri                           13      35
Bali United FC      Kapten I Wayan Dipta             17      38

In [5]:
df.groupby(['stadium','home']).agg({'week':'count'})

                                                   week
stadium                       home
Batakan                       Borneo FC Samarinda     4
                              PSM Makassar            5
Brawijaya                     Persik Kediri          17
Demang Lehman                 PS Barito Putera       11
Gelora B. J. Habibie          PSM Makassar           11
Gelora Bandung Lautan Api     Persib Bandung         12
Gelora Bangkalan              Madura United FC       12
Gelora Bung Karno             Persija Jakarta         5
Gelora Bung Tomo              Persebaya Surabaya     16
Gelora Madura Ratu Pamelingan Madura United FC        4
Indomilk Arena                Dewa United FC         16
                              Persita Tangerang      15
Jatidiri                      PSIS Semarang          13
Kapten I Wayan Dipta          Arema FC               17
                              Bali United FC         17
                              Persija Jakarta         3
                              Persikabo 1973          2
                              Persis Solo             1
                              Persita Tangerang       1
Maguwoharjo                   PSS Sleman             11
                              Persis Solo             2
                              Rans Nusantara FC      11
Manahan                       PSS Sleman              4
                              Persis Solo            13
Pakansari                     Persikabo 1973          2
Patriot Chandra Bhaga         Bhayangkara FC         12
                              Persija Jakarta         8
STIK Jakarta                  Bhayangkara FC          4
Segiri                        Borneo FC Samarinda    13
Si Jalak Harupat              Persib Bandung          5
Sriwedari                     Persis Solo             1
Sultan Agung                  PS Barito Putera        6
                              PSS Sleman              1
                              Persikabo 1973          2
                              Rans Nusantara FC       6
Wibawa Mukti                  Persikabo 1973         10
dr. H. Moch. Soebroto         PSIS Semarang           4

In [6]:
df.groupby(['away']).agg({'week':'count', 'apoint':'sum'})

                     week  apoint
away
Arema FC               16      15
Bali United FC         16      20
Bhayangkara FC         17      13
Borneo FC Samarinda    16      29
Dewa United FC         17      23
Madura United FC       17      24
PS Barito Putera       16      10
PSIS Semarang          16      14
PSM Makassar           17      13
PSS Sleman             17      16
Persebaya Surabaya     17      15
Persib Bandung         16      30
Persija Jakarta        17      17
Persik Kediri          16      15
Persikabo 1973         17       8
Persis Solo            16      11
Persita Tangerang      17      11
Rans Nusantara FC      16      16

In [7]:
df.groupby(['away']).agg({'week':'count', 'apoint':'sum'}).sort_values(by='apoint')

                     week  apoint
away
Persikabo 1973         17       8
PS Barito Putera       16      10
Persis Solo            16      11
Persita Tangerang      17      11
PSM Makassar           17      13
Bhayangkara FC         17      13
PSIS Semarang          16      14
Persik Kediri          16      15
Persebaya Surabaya     17      15
Arema FC               16      15
PSS Sleman             17      16
Rans Nusantara FC      16      16
Persija Jakarta        17      17
Bali United FC         16      20
Dewa United FC         17      23
Madura United FC       17      24
Borneo FC Samarinda    16      29
Persib Bandung         16      30

# homebase

In [9]:
hbdf = pd.read_csv('homebase.csv', comment='#', escapechar='\t')
hbdf.rename(columns=lambda x: x.strip('\t ') if isinstance(x, str) else x, inplace=True)

for col in hbdf.columns:
    hbdf[col] = hbdf[col].apply(lambda x: x.strip('\t')if isinstance(x, str) else x)
    hbdf[col] = hbdf[col].apply(lambda x: x.lstrip() if isinstance(x, str) else x)
hbdf

,club,homebase,city,homelib,citylib,played,falsehome,dom
0,Arema FC,Kanjuruhan,Malang,Kanjuruhan,Malang,no,Kapten I Wayan Dipta,Gianyar
1,Bali United FC,Kapten I Wayan Dipta,Gianyar,Kapten I Wayan Dipta,Gianyar,yes,NaN,NaN
2,Bhayangkara FC,Patriot Chandra Bhaga,Bekasi,Wibawa Mukti,Bekasi,yesn,STIK Jakarta,Jakarta Selatan
3,Borneo FC Samarinda,Segiri,Samarinda,Segiri,Samarinda,yesn,Batakan,Balikpapan
4,Dewa United FC,Indomilk Arena,Tangerang,Indomilk Arena,Tangerang,yes,NaN,NaN
5,Madura United FC,Gelora Bangkalan,Bangkalan,Gelora Madura Ratu Pamelingan,Pamekasan,yes,NaN,NaN
6,PS Barito Putera,17 Mei,Banjarmasin,Demang Lehman,Martapura,yesn,Sultan Agung,Bantul
7,PSIS Semarang,Citarum,Semarang,Jatidiri,Semarang,yesn,dr. H. Moch. Soebroto,Magelang
8,PSM Makassar,Andi Mattalatta Mattoanging,Makassar,Gelora B. J. Habibie,Pare-pare,yesn,Batakan,Balikpapan
9,PSS Sleman,Maguwoharjo,Sleman,Maguwoharjo,Sleman,yesn,Sultan Agung,Bantul
10,Persebaya Surabaya,Gelora Bung Tomo,Surabaya,Gelora Bung Tomo,Surabaya,yes,NaN,NaN
11,Persib Bandung,Gelora Bandung Lautan Api,Bandung,Gelora Bandung Lautan Api,Bandung,yesn,Si Jalak Harupat,Bandung
12,Persija Jakarta,Gelora Bung Karno,Jakarta Pusat,Patriot Chandra Bhaga,Bekasi,yes,NaN,NaN
13,Persik Kediri,Brawijaya,Kediri,Brawijaya,Kediri,yes,NaN,NaN
14,Persikabo 1973,Pakansari,Bogor,Pakansari,Bogor,yesn,Wibawa Mukti,Bekasi
15,Persis Solo,Manahan,Solo,Manahan,Solo,yesn,Sriwedari,Solo
16,Persita Tangerang,Indomilk Arena,Tangerang,Indomilk Arena,Tangerang,yes,NaN,NaN
17,Rans Nusantara FC,Maguwoharjo,Sleman,Maguwoharjo,Sleman,yesn,Sultan Agung,Bantul

In [10]:
hbdf['city'].values#.apply(lambda x: x.lstrip()if isinstance(x, str) else x)

array(['Malang', 'Gianyar', 'Bekasi', 'Samarinda', 'Tangerang',
       'Bangkalan', 'Banjarmasin', 'Semarang', 'Makassar', 'Sleman',
       'Surabaya', 'Bandung', 'Jakarta Pusat', 'Kediri', 'Bogor', 'Solo',
       'Tangerang', 'Sleman'], dtype=object)

# points earned at

## algorithm cekson

In [29]:
matches = df.loc[df.home.str.contains('Rans')]
matches

,week,day,month,year,home,hscore,hmatch,hpoint,htotal,away,ascore,amatch,apoint,atotal,stadium,city
5,1,3,7,2023,Rans Nusantara FC,2,1,3,3,Persikabo 1973,1,1,0,0,Maguwoharjo,Sleman
21,3,15,7,2023,Rans Nusantara FC,0,2,0,6,Persita Tangerang,1,2,3,6,Maguwoharjo,Sleman
41,5,30,7,2023,Rans Nusantara FC,0,3,1,8,PSS Sleman,0,3,1,6,Maguwoharjo,Sleman
61,7,9,8,2023,Rans Nusantara FC,3,4,3,12,Madura United FC,1,4,0,13,Maguwoharjo,Sleman
76,9,19,8,2023,Rans Nusantara FC,0,5,1,16,Dewa United FC,0,5,1,12,Maguwoharjo,Sleman
93,11,2,9,2023,Rans Nusantara FC,1,6,3,19,Persik Kediri,0,6,0,12,Maguwoharjo,Sleman
108,13,22,9,2023,Rans Nusantara FC,1,7,0,22,Persis Solo,2,7,3,18,Maguwoharjo,Sleman
126,15,6,10,2023,Rans Nusantara FC,2,8,3,26,PSIS Semarang,1,7,0,24,Maguwoharjo,Sleman
151,17,30,10,2023,Rans Nusantara FC,1,9,1,30,PSM Makassar,1,10,1,22,Maguwoharjo,Sleman
167,19,9,11,2023,Rans Nusantara FC,1,10,1,31,Bhayangkara FC,1,9,1,9,Maguwoharjo,Sleman
178,21,1,12,2023,Rans Nusantara FC,0,11,1,32,Persebaya Surabaya,0,11,1,23,Maguwoharjo,Sleman
197,23,16,12,2023,Rans Nusantara FC,0,12,0,32,Borneo FC Samarinda,1,11,3,51,Sultan Agung,Bantul
219,25,22,2,2024,Rans Nusantara FC,2,13,0,33,Arema FC,3,12,3,24,Sultan Agung,Bantul
240,27,3,3,2024,Rans Nusantara FC,0,14,0,33,Persib Bandung,4,14,3,48,Sultan Agung,Bantul

In [15]:
hdetails = hbdf.loc[hbdf.club.str.contains('Persija')]
hdetails

,club,homebase,city,homelib,citylib,played,falsehome,dom
12,Persija Jakarta,Gelora Bung Karno,Jakarta Pusat,Patriot Chandra Bhaga,Bekasi,yes,NaN,NaN

In [16]:
masks = matches.loc[matches['stadium'] == hdetails['homebase'].values[0]]
masks

Empty DataFrame
Columns: [week, day, month, year, home, hscore, hmatch, hpoint, htotal, away, ascore, amatch, apoint, atotal, stadium, city]
Index: []

In [17]:
pointsathome = masks['hpoint'].sum()
pointsathome

0

In [19]:
falsehome = matches.loc[matches['stadium'] == hdetails['falsehome'].values[0]]
pointsfalsehome = falsehome['hpoint'].sum()
pointsfalsehome

0

In [20]:
#amatches = df.loc[df.away.str.contains('Persija')]
#amasks = matches.loc[matches['stadium'] == hdetails['homebase'].values[0]]
pointsaway = df.loc[df.away.str.contains('Persija')]['apoint'].sum()
pointsaway

7

In [21]:
df.loc[df.away.str.contains('Persija')]

,week,day,month,year,home,hscore,hmatch,hpoint,htotal,away,ascore,amatch,apoint,atotal,stadium,city
17,2,9,7,2023,Persikabo 1973,0,1,1,1,Persija Jakarta,0,1,1,2,Pakansari,Bogor
31,4,22,7,2023,Persita Tangerang,1,2,3,9,Persija Jakarta,0,2,0,5,Indomilk Arena,Tangerang
51,6,4,8,2023,PSS Sleman,1,3,0,6,Persija Jakarta,3,3,3,11,Maguwoharjo,Sleman
68,8,13,8,2023,Madura United FC,2,4,3,16,Persija Jakarta,0,4,0,12,Gelora Bangkalan,Bangkalan
83,10,25,8,2023,Dewa United FC,2,5,3,15,Persija Jakarta,0,5,0,13,Indomilk Arena,Tangerang
106,12,17,9,2023,Persik Kediri,1,6,0,12,Persija Jakarta,2,6,3,17,Brawijaya,Kediri

## points earned at home/away

In [10]:
homepoints  = []
awaypoints  = []
fhomepoints = []
totalpoints = []
thpoints    = []

for cl, std, city, dom in zip (hbdf['club'], hbdf['homebase'], hbdf['city'], hbdf['dom']):
    
    if 'Madura' in cl:
        hpe  = df.loc[( (df['home']==cl) & ( (df['stadium']==std)|(df['city']==dom) ) )]['hpoint'].sum()
        fhpe = df.loc[( (df['home']==cl) & ( (df['stadium']!=std)&(df['city']!=dom) ) )]['hpoint'].sum()
        
    else:
        hpe  = df.loc[( (df['home']==cl) & ( (df['stadium']==std)|(city==dom) ) )]['hpoint'].sum()
        fhpe = df.loc[( (df['home']==cl) & ( (df['stadium']!=std)&(city!=dom) ) )]['hpoint'].sum()
            
    ape  = df.loc[(df['away']==cl)]['apoint'].sum()
    
    homepoints.append(hpe)
    fhomepoints.append(fhpe)
    awaypoints.append(ape)
    
    thpoints.append(hpe+fhpe)
    
    totalpoints.append(hpe+fhpe+ape)

In [11]:
klsmn = pd.DataFrame ( {'Club': hbdf['club'],
                        'Home Points': homepoints,
                        'False Home Points': fhomepoints,
                        'Away Points': awaypoints,
                        'Total Points': totalpoints,
                        'th': thpoints
})
klsmn

,Club,Home Points,False Home Points,Away Points,Total Points,th
0,Arema FC,0,22,15,37,22
1,Bali United FC,38,0,20,58,38
2,Bhayangkara FC,7,3,13,23,10
3,Borneo FC Samarinda,35,6,29,70,41
4,Dewa United FC,28,0,23,51,28
5,Madura United FC,24,6,24,54,30
6,PS Barito Putera,0,33,10,43,33
7,PSIS Semarang,0,39,14,53,39
8,PSM Makassar,0,28,13,41,28
9,PSS Sleman,15,5,16,36,20
10,Persebaya Surabaya,24,0,15,39,24
11,Persib Bandung,32,0,30,62,32
12,Persija Jakarta,8,20,17,45,28
13,Persik Kediri,33,0,15,48,33
14,Persikabo 1973,1,11,8,20,12
15,Persis Solo,36,0,11,47,36
16,Persita Tangerang,24,1,11,36,25
17,Rans Nusantara FC,17,2,16,35,19

In [24]:
print(homepoints,
      awaypoints,
      fhomepoints,
      totalpoints,
      thpoints)

[0, 13, 1, 16, 11, 10, 0, 0, 0, 7, 11, 10, 4, 8, 1, 13, 6, 11] [5, 4, 5, 6, 6, 10, 5, 5, 9, 10, 7, 8, 7, 4, 6, 2, 5, 11] [5, 0, 0, 0, 0, 6, 15, 13, 9, 0, 0, 0, 6, 0, 2, 0, 0, 0] [10, 17, 6, 22, 17, 26, 20, 18, 18, 17, 18, 18, 17, 12, 9, 15, 11, 22] [5, 13, 1, 16, 11, 16, 15, 13, 9, 7, 11, 10, 10, 8, 3, 13, 6, 11]

In [25]:
print(hbdf['club'].values,
      homepoints,
      awaypoints,
      fhomepoints,
      totalpoints,
      thpoints)

['Arema FC' 'Bali United FC' 'Bhayangkara FC' 'Borneo FC Samarinda'
 'Dewa United FC' 'Madura United FC' 'PS Barito Putera' 'PSIS Semarang'
 'PSM Makassar' 'PSS Sleman' 'Persebaya Surabaya' 'Persib Bandung'
 'Persija Jakarta' 'Persik Kediri' 'Persikabo 1973' 'Persis Solo'
 'Persita Tangerang' 'Rans Nusantara FC'] [0, 13, 1, 16, 11, 10, 0, 0, 0, 7, 11, 10, 4, 8, 1, 13, 6, 11] [5, 4, 5, 6, 6, 10, 5, 5, 9, 10, 7, 8, 7, 4, 6, 2, 5, 11] [5, 0, 0, 0, 0, 6, 15, 13, 9, 0, 0, 0, 6, 0, 2, 0, 0, 0] [10, 17, 6, 22, 17, 26, 20, 18, 18, 17, 18, 18, 17, 12, 9, 15, 11, 22] [5, 13, 1, 16, 11, 16, 15, 13, 9, 7, 11, 10, 10, 8, 3, 13, 6, 11]

# points lost at

## algorithm cekson

In [26]:
df.loc[( (df['home']=='Persis Solo') & ( (df['stadium']=='Manahan')|(hbdf['city']=='Solo') ) )]#['hpoint'].count()*3

,week,day,month,year,home,hscore,hmatch,hpoint,htotal,away,ascore,amatch,apoint,atotal,stadium,city
1,1,1,7,2023,Persis Solo,2,1,0,0,Persebaya Surabaya,3,1,3,3,Manahan,Solo
23,3,15,7,2023,Persis Solo,2,2,3,4,Borneo FC Samarinda,1,2,0,4,Manahan,Solo
58,7,8,8,2023,Persis Solo,2,4,3,9,Persib Bandung,1,4,0,7,Manahan,Solo
78,9,19,8,2023,Persis Solo,3,5,3,12,Bali United FC,1,4,0,14,Manahan,Solo
104,12,16,9,2023,Persis Solo,2,6,3,15,PSIS Semarang,0,6,0,18,Manahan,Solo

In [27]:
ceka=df.loc[( (df['home']=='Persis Solo') & ( (df['stadium']=='Manahan')|(hbdf['city']=='Solo') ) )]['hpoint'].count()*3
cekb=df.loc[( (df['home']=='Persis Solo') & ( (df['stadium']=='Manahan')|(hbdf['city']=='Solo') ) )]['hpoint'].sum()
print(ceka,
      cekb)
cekc=ceka-cekb
print (cekc)

15 12
3

In [28]:
ceka=df.loc[( (df['home']=='Arema FC') & (df['stadium']!='Gajayana') )]['hpoint'].count()*3
cekb=df.loc[( (df['home']=='Arema FC') & (df['stadium']!='Gajayana') )]['hpoint'].sum()
print(ceka,
      cekb)
cekc=ceka-cekb
print (cekc)

18 5
13

In [29]:
print(df.loc[( (df['home']=='Madura United FC') & ( (df['stadium']=='Gelora Bangkalan')|(df['city']=='Pamekasan') ) )]['hpoint'].count()*3,
      df.loc[( (df['home']=='Madura United FC') & ( (df['stadium']=='Gelora Bangkalan')|(df['city']=='Pamekasan') ) )]['hpoint'].sum())

18 16

## points lost at home/away

In [12]:
def itung (syrt):
    earned = syrt.sum()#df.loc[syrt]['hpoint'].sum()
    fulll = syrt.count()*3#df.loc[syrt]['hpoint'].count()*3
    lost = fulll-earned
    return (lost)

In [13]:
homelost  = []
awaylost  = []
fhomelost = []
totallost = []
thlost    = []
for cl, std, city, dom in zip (hbdf['club'], hbdf['homebase'], hbdf['city'], hbdf['dom']):
    
    if 'Madura' in cl or city==dom:
        print('if',cl)
        # points earned
        #hpe  = df.loc[( (df['home']==cl) & ( (df['stadium']==std)|(df['city']==dom) ) )]['hpoint'].sum()
        #fhpe = df.loc[( (df['home']==cl) & ( (df['stadium']!=std)&(df['city']!=dom) ) )]['hpoint'].sum()
        # total played
        #hpfull  = df.loc[( (df['home']==cl) & ( (df['stadium']==std)|(df['city']==dom) ) )]['hpoint'].count()*3
        #fhpfull = df.loc[( (df['home']==cl) & ( (df['stadium']!=std)&(df['city']!=dom) ) )]['hpoint'].count()*3
        # points lost
        #hplost  = hpfull-hpe
        #fhplost = fhpfull-fhpe
        hplost = itung(df.loc[( (df['home']==cl) & ( (df['stadium']==std)|(df['city']==dom) ) )]['hpoint'])
        fhplost = itung(df.loc[( (df['home']==cl) & ( (df['stadium']!=std)&(df['city']!=dom) ) )]['hpoint'])
        
    else:
        print('else',cl)
        # points earned
        #hpe  = df.loc[( (df['home']==cl) & (df['stadium']==std) )]['hpoint'].sum()
        #fhpe = df.loc[( (df['home']==cl) & (df['stadium']!=std) )]['hpoint'].sum()
        #print('point earned', fhpe)
        # total played
        #hpfull  = df.loc[( (df['home']==cl) & (df['stadium']==std) )]['hpoint'].count()*3
        #fhpfull = df.loc[( (df['home']==cl) & (df['stadium']!=std) )]['hpoint'].count()*3
        #print('point full', fhpfull)
        # points lost
        #hplost  = hpfull-hpe
        #fhplost = fhpfull-fhpe
        #print('point lost', fhplost)
        hplost  = itung(df.loc[( (df['home']==cl) & (df['stadium']==std) )]['hpoint'])
        fhplost = itung(df.loc[( (df['home']==cl) & (df['stadium']!=std) )]['hpoint'])
            
    #ape  = df.loc[(df['away']==cl)]['apoint'].sum()
    #apfull = df.loc[(df['away']==cl)]['apoint'].count()*3
    aplost = itung(df.loc[(df['away']==cl)]['apoint'])
    
    homelost.append(hplost)
    fhomelost.append(fhplost)
    awaylost.append(aplost)
    
    thlost.append(hplost+fhplost)
    
    totallost.append(hplost+fhplost+aplost)

else Arema FC
else Bali United FC
else Bhayangkara FC
else Borneo FC Samarinda
else Dewa United FC
if Madura United FC
else PS Barito Putera
else PSIS Semarang
else PSM Makassar
else PSS Sleman
else Persebaya Surabaya
if Persib Bandung
else Persija Jakarta
else Persik Kediri
else Persikabo 1973
if Persis Solo
else Persita Tangerang
else Rans Nusantara FC

In [14]:
lostpoints = pd.DataFrame ( {'Club': hbdf['club'],
                        'Home lost': homelost,
                        'False Home lost': fhomelost,
                        'Away lost': awaylost,
                        'Total lost': totallost,
                        'th lost': thlost
})
lostpoints

,Club,Home lost,False Home lost,Away lost,Total lost,th lost
0,Arema FC,0,29,33,62,29
1,Bali United FC,13,0,28,41,13
2,Bhayangkara FC,29,9,38,76,38
3,Borneo FC Samarinda,4,6,19,29,10
4,Dewa United FC,20,0,28,48,20
5,Madura United FC,12,6,27,45,18
6,PS Barito Putera,0,18,38,56,18
7,PSIS Semarang,0,12,34,46,12
8,PSM Makassar,0,20,38,58,20
9,PSS Sleman,18,10,35,63,28
10,Persebaya Surabaya,24,0,36,60,24
11,Persib Bandung,19,0,18,37,19
12,Persija Jakarta,7,13,34,54,20
13,Persik Kediri,18,0,33,51,18
14,Persikabo 1973,5,31,43,79,36
15,Persis Solo,13,2,37,52,15
16,Persita Tangerang,21,2,40,63,23
17,Rans Nusantara FC,16,16,32,64,32

In [15]:
print(hbdf['club'].values,
      homelost,
      awaylost,
      fhomelost,
      totallost,
      thlost)

['Arema FC' 'Bali United FC' 'Bhayangkara FC' 'Borneo FC Samarinda'
 'Dewa United FC' 'Madura United FC' 'PS Barito Putera' 'PSIS Semarang'
 'PSM Makassar' 'PSS Sleman' 'Persebaya Surabaya' 'Persib Bandung'
 'Persija Jakarta' 'Persik Kediri' 'Persikabo 1973' 'Persis Solo'
 'Persita Tangerang' 'Rans Nusantara FC'] [0, 13, 29, 4, 20, 12, 0, 0, 0, 18, 24, 19, 7, 18, 5, 13, 21, 16] [33, 28, 38, 19, 28, 27, 38, 34, 38, 35, 36, 18, 34, 33, 43, 37, 40, 32] [29, 0, 9, 6, 0, 6, 18, 12, 20, 10, 0, 0, 13, 0, 31, 2, 2, 16] [62, 41, 76, 29, 48, 45, 56, 46, 58, 63, 60, 37, 54, 51, 79, 52, 63, 64] [29, 13, 38, 10, 20, 18, 18, 12, 20, 28, 24, 19, 20, 18, 36, 15, 23, 32]

## check

In [16]:
lostpoints['Total lost']

0     62
1     41
2     76
3     29
4     48
5     45
6     56
7     46
8     58
9     63
10    60
11    37
12    54
13    51
14    79
15    52
16    63
17    64
Name: Total lost, dtype: int64

In [17]:
klsmn['Total Points']+lostpoints['Total lost']

0     99
1     99
2     99
3     99
4     99
5     99
6     99
7     99
8     99
9     99
10    99
11    99
12    99
13    99
14    99
15    99
16    99
17    99
dtype: int64